name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your project’s Python version

      - name: Install Dependencies Locally
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          source: "."
          target: "/var/www/efficient_corporates_project"  # Path on the droplet

      - name: SSH and Restart Services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_DROPLET_IP }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/efficient_corporates_project
            python3 -m venv venv  # Create virtual environment
            source venv/bin/activate  # Activate virtual environment
            pip install --upgrade pip  # Ensure pip is updated
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            systemctl restart gunicorn
            systemctl restart nginx
